# Generated by Django 4.2 on 2023-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.IntegerField(blank=True)),
                ('start_time', models.IntegerField(blank=True)),
                ('isOn', models.BooleanField(default=False)),
                ('ssid', models.CharField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('temp', models.FloatField(blank=True)),
            ],
        ),
    ]
